// <auto-generated />
using System;
using Oge.Refining.CaseApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Oge.Refining.CaseApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CaseDbContext))]
    [Migration("20260815181709_AddRootCauseScenario")]
    partial class AddRootCauseScenario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Oge.Refining.CaseApp.Infrastructure.Data.CaseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessUnitName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("RefineryName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("RegulatoryNotifiable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.ToTable("Cases", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CaseNumber = "SYN-2026-0017",
                            Description = "At 14:27 UTC, reduced cooling-water flow raised crude tower overhead pressure to 2.4 bar and activated the high-high pressure safeguard. The investigation links the loss of condenser duty to cooling-water pump P-204B and precursor case SYN-2026-0009. Feed was cut automatically, vapour was routed to flare for eleven minutes, and no personnel exposure occurred.",
                            ProcessUnitName = "Crude Distillation Unit 1",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = true,
                            ReportedAt = new DateTime(2026, 8, 6, 14, 35, 0, 0, DateTimeKind.Utc),
                            Severity = "Critical",
                            Status = "Open",
                            Title = "Crude tower overhead pressure excursion",
                            Type = "Incident",
                            UpdatedAt = new DateTime(2026, 8, 8, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CaseNumber = "SYN-2026-0016",
                            Description = "A synthetic procedure review identified an incomplete temperature-equilibration record.",
                            ProcessUnitName = "Fluid Catalytic Cracker 2",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = false,
                            ReportedAt = new DateTime(2026, 8, 5, 10, 20, 0, 0, DateTimeKind.Utc),
                            Severity = "Moderate",
                            Status = "InProgress",
                            Title = "Catalyst loading procedure deviation",
                            Type = "NonConformance",
                            UpdatedAt = new DateTime(2026, 8, 5, 13, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CaseNumber = "SYN-2026-0012",
                            Description = "A fictional field observation was corrected immediately during a routine inspection.",
                            ProcessUnitName = "Hydrotreater A",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = false,
                            ReportedAt = new DateTime(2026, 7, 28, 11, 45, 0, 0, DateTimeKind.Utc),
                            Severity = "Minor",
                            Status = "Closed",
                            Title = "Inspection eyewear observation",
                            Type = "SafetyObservation",
                            UpdatedAt = new DateTime(2026, 7, 28, 14, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CaseNumber = "SYN-2026-0009",
                            Description = "Cooling-water pump P-204B outboard-bearing vibration increased from 4.1 to 8.7 mm/s over fourteen days, above the 7.1 mm/s review threshold. Inspection was deferred while a replacement bearing was sourced; the case is a precursor to incident SYN-2026-0017.",
                            ProcessUnitName = "Utilities Area",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = false,
                            ReportedAt = new DateTime(2026, 7, 21, 8, 10, 0, 0, DateTimeKind.Utc),
                            Severity = "Major",
                            Status = "OnHold",
                            Title = "Cooling-water pump vibration trend",
                            Type = "MaintenanceIssue",
                            UpdatedAt = new DateTime(2026, 7, 21, 11, 10, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Oge.Refining.CaseApp.Infrastructure.Data.CaseTimelineRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("CaseTimelineEntries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AuthorName = "Control System Historian",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Cooling-water header pressure began falling from 5.1 bar; pump P-204B motor current fell from 42 A to 31 A while the standby pump remained in manual mode.",
                            EntryType = "ProcessData",
                            OccurredAt = new DateTime(2026, 8, 6, 13, 55, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AuthorName = "Control System Historian",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Overhead condenser outlet temperature rose from its 35 C baseline to 46 C. Pressure controller PC-101 output reached 92 percent.",
                            EntryType = "Alarm",
                            OccurredAt = new DateTime(2026, 8, 6, 14, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AuthorName = "Shift Supervisor",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Tower pressure reached the 2.4 bar high-high set point. The safeguard cut unit feed and routed vapour to flare; pressure returned below 1.9 bar at 14:38 UTC.",
                            EntryType = "Safeguard",
                            OccurredAt = new DateTime(2026, 8, 6, 14, 27, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            AuthorName = "Synthetic Reporter",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Incident opened after unit stabilization. No injury or exposure was reported; the eleven-minute flare event was referred for regulatory review.",
                            EntryType = "Reported",
                            OccurredAt = new DateTime(2026, 8, 6, 14, 35, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            AuthorName = "Rotating Equipment Engineer",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "P-204B was isolated. The outboard bearing had spalled rollers and heat discoloration; measured radial clearance was 0.31 mm against a 0.08-0.15 mm specification.",
                            EntryType = "Inspection",
                            OccurredAt = new DateTime(2026, 8, 6, 16, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            AuthorName = "Reliability Engineer",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Case SYN-2026-0009 recorded vibration rising from 4.1 to 8.7 mm/s. Inspection was deferred pending parts, and the operating log contained no compensating monitoring frequency or automatic standby-pump requirement.",
                            EntryType = "RecordsReview",
                            OccurredAt = new DateTime(2026, 8, 6, 17, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            AuthorName = "Investigation Lead",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "The board operator confirmed P-204A was available but its selector was left in manual after seal work. The low-header-pressure alarm required manual pump transfer and was acknowledged during simultaneous unit alarms.",
                            EntryType = "Interview",
                            OccurredAt = new DateTime(2026, 8, 7, 9, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            AuthorName = "Investigation Team",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Direct cause: P-204B bearing degradation reduced cooling-water flow and condenser duty. Root cause: the vibration-threshold deferral process allowed continued operation without risk-based approval or compensating controls. Contributing factor: P-204A was not configured for automatic transfer.",
                            EntryType = "RootCause",
                            OccurredAt = new DateTime(2026, 8, 7, 14, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            AuthorName = "Operations Manager",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "P-204B bearing replacement and P-204A automatic-transfer testing were assigned before restart. The maintenance-deferral procedure will require accountable approval, an expiry date, and documented compensating controls.",
                            EntryType = "CorrectiveAction",
                            OccurredAt = new DateTime(2026, 8, 7, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            AuthorName = "Process Safety Manager",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Effectiveness checks: verify weekly vibration remains below 4.5 mm/s for 30 days, function-test automatic transfer twice, and audit all open rotating-equipment deferrals by 2026-08-21.",
                            EntryType = "VerificationPlan",
                            OccurredAt = new DateTime(2026, 8, 8, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            AuthorName = "Synthetic Reporter",
                            CaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "Case created from fictional demonstration data.",
                            EntryType = "Reported",
                            OccurredAt = new DateTime(2026, 8, 5, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            AuthorName = "Synthetic Review Team",
                            CaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "Initial review completed for demonstration purposes.",
                            EntryType = "Review",
                            OccurredAt = new DateTime(2026, 8, 5, 13, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AuthorName = "Synthetic Reporter",
                            CaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Content = "Case created from fictional demonstration data.",
                            EntryType = "Reported",
                            OccurredAt = new DateTime(2026, 7, 28, 11, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AuthorName = "Synthetic Review Team",
                            CaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Content = "Initial review completed for demonstration purposes.",
                            EntryType = "Review",
                            OccurredAt = new DateTime(2026, 7, 28, 14, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            AuthorName = "Synthetic Reporter",
                            CaseId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Content = "Case created from fictional demonstration data.",
                            EntryType = "Reported",
                            OccurredAt = new DateTime(2026, 7, 21, 8, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            AuthorName = "Synthetic Review Team",
                            CaseId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Content = "Initial review completed for demonstration purposes.",
                            EntryType = "Review",
                            OccurredAt = new DateTime(2026, 7, 21, 11, 10, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Oge.Refining.CaseApp.Infrastructure.Data.CaseTimelineRecord", b =>
                {
                    b.HasOne("Oge.Refining.CaseApp.Infrastructure.Data.CaseRecord", "Case")
                        .WithMany("Timeline")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Oge.Refining.CaseApp.Infrastructure.Data.CaseRecord", b =>
                {
                    b.Navigation("Timeline");
                });
#pragma warning restore 612, 618
        }
    }
}
