// <auto-generated />
using System;
using Oge.Refining.CaseApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Oge.Refining.CaseApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CaseDbContext))]
    [Migration("20260809133129_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Oge.Refining.CaseApp.Infrastructure.Data.CaseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessUnitName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("RefineryName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("RegulatoryNotifiable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.ToTable("Cases", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CaseNumber = "SYN-2026-0017",
                            Description = "A synthetic pressure excursion triggered an automatic unit response. No personnel exposure occurred.",
                            ProcessUnitName = "Crude Distillation Unit 1",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = true,
                            ReportedAt = new DateTime(2026, 8, 6, 14, 35, 0, 0, DateTimeKind.Utc),
                            Severity = "Critical",
                            Status = "Open",
                            Title = "Crude tower overhead pressure excursion",
                            Type = "Incident",
                            UpdatedAt = new DateTime(2026, 8, 6, 17, 35, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CaseNumber = "SYN-2026-0016",
                            Description = "A synthetic procedure review identified an incomplete temperature-equilibration record.",
                            ProcessUnitName = "Fluid Catalytic Cracker 2",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = false,
                            ReportedAt = new DateTime(2026, 8, 5, 10, 20, 0, 0, DateTimeKind.Utc),
                            Severity = "Moderate",
                            Status = "InProgress",
                            Title = "Catalyst loading procedure deviation",
                            Type = "NonConformance",
                            UpdatedAt = new DateTime(2026, 8, 5, 13, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CaseNumber = "SYN-2026-0012",
                            Description = "A fictional field observation was corrected immediately during a routine inspection.",
                            ProcessUnitName = "Hydrotreater A",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = false,
                            ReportedAt = new DateTime(2026, 7, 28, 11, 45, 0, 0, DateTimeKind.Utc),
                            Severity = "Minor",
                            Status = "Closed",
                            Title = "Inspection eyewear observation",
                            Type = "SafetyObservation",
                            UpdatedAt = new DateTime(2026, 7, 28, 14, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CaseNumber = "SYN-2026-0009",
                            Description = "Synthetic vibration readings exceeded the fictional review threshold pending a planned inspection.",
                            ProcessUnitName = "Utilities Area",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = false,
                            ReportedAt = new DateTime(2026, 7, 21, 8, 10, 0, 0, DateTimeKind.Utc),
                            Severity = "Major",
                            Status = "OnHold",
                            Title = "Cooling-water pump vibration trend",
                            Type = "MaintenanceIssue",
                            UpdatedAt = new DateTime(2026, 7, 21, 11, 10, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Oge.Refining.CaseApp.Infrastructure.Data.CaseTimelineRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("CaseTimelineEntries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AuthorName = "Synthetic Reporter",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Case created from fictional demonstration data.",
                            EntryType = "Reported",
                            OccurredAt = new DateTime(2026, 8, 6, 14, 35, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AuthorName = "Synthetic Review Team",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Initial review completed for demonstration purposes.",
                            EntryType = "Review",
                            OccurredAt = new DateTime(2026, 8, 6, 17, 35, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            AuthorName = "Synthetic Reporter",
                            CaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "Case created from fictional demonstration data.",
                            EntryType = "Reported",
                            OccurredAt = new DateTime(2026, 8, 5, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            AuthorName = "Synthetic Review Team",
                            CaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "Initial review completed for demonstration purposes.",
                            EntryType = "Review",
                            OccurredAt = new DateTime(2026, 8, 5, 13, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AuthorName = "Synthetic Reporter",
                            CaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Content = "Case created from fictional demonstration data.",
                            EntryType = "Reported",
                            OccurredAt = new DateTime(2026, 7, 28, 11, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AuthorName = "Synthetic Review Team",
                            CaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Content = "Initial review completed for demonstration purposes.",
                            EntryType = "Review",
                            OccurredAt = new DateTime(2026, 7, 28, 14, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            AuthorName = "Synthetic Reporter",
                            CaseId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Content = "Case created from fictional demonstration data.",
                            EntryType = "Reported",
                            OccurredAt = new DateTime(2026, 7, 21, 8, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            AuthorName = "Synthetic Review Team",
                            CaseId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Content = "Initial review completed for demonstration purposes.",
                            EntryType = "Review",
                            OccurredAt = new DateTime(2026, 7, 21, 11, 10, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Oge.Refining.CaseApp.Infrastructure.Data.CaseTimelineRecord", b =>
                {
                    b.HasOne("Oge.Refining.CaseApp.Infrastructure.Data.CaseRecord", "Case")
                        .WithMany("Timeline")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Oge.Refining.CaseApp.Infrastructure.Data.CaseRecord", b =>
                {
                    b.Navigation("Timeline");
                });
#pragma warning restore 612, 618
        }
    }
}
