// <auto-generated />
using System;
using Oge.Refining.CaseApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Oge.Refining.CaseApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CaseDbContext))]
    [Migration("20260909104826_RefreshDemoData")]
    partial class RefreshDemoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Oge.Refining.CaseApp.Infrastructure.Data.CaseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessUnitName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("RefineryName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("RegulatoryNotifiable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.ToTable("Cases", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CaseNumber = "SYN-2026-0017",
                            Description = "At 14:27 UTC, crude tower overhead pressure reached 2.4 bar and activated the high-high pressure safeguard during a period of reduced cooling-water flow. Feed was cut automatically, vapour was routed to flare for eleven minutes, and no personnel exposure occurred. Equipment history for pump P-204B is recorded in case SYN-2026-0009.",
                            ProcessUnitName = "Crude Distillation Unit 1",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = true,
                            ReportedAt = new DateTime(2026, 9, 3, 14, 35, 0, 0, DateTimeKind.Utc),
                            Severity = "Critical",
                            Status = "Open",
                            Title = "Crude tower overhead pressure excursion",
                            Type = "Incident",
                            UpdatedAt = new DateTime(2026, 9, 8, 9, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CaseNumber = "SYN-2026-0016",
                            Description = "Temperature-equilibration evidence was missing from the catalyst loading record. The review is reconciling batch historian data with operator logs before disposition.",
                            ProcessUnitName = "Fluid Catalytic Cracker 2",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = false,
                            ReportedAt = new DateTime(2026, 9, 2, 10, 20, 0, 0, DateTimeKind.Utc),
                            Severity = "Moderate",
                            Status = "InProgress",
                            Title = "Catalyst loading procedure deviation",
                            Type = "NonConformance",
                            UpdatedAt = new DateTime(2026, 9, 7, 15, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CaseNumber = "SYN-2026-0012",
                            Description = "A contractor entered the sample station without sealed eyewear. Work stopped immediately, the PPE matrix was clarified, and the observation was closed after a field verification.",
                            ProcessUnitName = "Hydrotreater A",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = false,
                            ReportedAt = new DateTime(2026, 8, 26, 11, 45, 0, 0, DateTimeKind.Utc),
                            Severity = "Minor",
                            Status = "Closed",
                            Title = "Inspection eyewear observation",
                            Type = "SafetyObservation",
                            UpdatedAt = new DateTime(2026, 8, 27, 14, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CaseNumber = "SYN-2026-0009",
                            Description = "Cooling-water pump P-204B outboard-bearing vibration increased from 4.1 to 8.7 mm/s over fourteen days, above the 7.1 mm/s review threshold. The bearing was replaced and the case closed after stable post-repair readings.",
                            ProcessUnitName = "Utilities Area",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = false,
                            ReportedAt = new DateTime(2026, 8, 20, 8, 10, 0, 0, DateTimeKind.Utc),
                            Severity = "Major",
                            Status = "Closed",
                            Title = "Cooling-water pump vibration trend",
                            Type = "MaintenanceIssue",
                            UpdatedAt = new DateTime(2026, 9, 7, 10, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CaseNumber = "SYN-2026-0018",
                            Description = "The final-effluent analyzer reported elevated oil-in-water readings during a calibration drift. Retained samples are under laboratory review and discharge remained within the containment route.",
                            ProcessUnitName = "Wastewater Treatment Unit",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = true,
                            ReportedAt = new DateTime(2026, 9, 4, 7, 40, 0, 0, DateTimeKind.Utc),
                            Severity = "Major",
                            Status = "Open",
                            Title = "Wastewater analyzer reporting excursion",
                            Type = "EnvironmentalConcern",
                            UpdatedAt = new DateTime(2026, 9, 8, 16, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CaseNumber = "SYN-2026-0019",
                            Description = "Low seal-gas pressure initiated an automatic compressor unload before hydrocarbon containment was challenged. The investigation is reviewing a regulator response delay.",
                            ProcessUnitName = "Hydrotreater B",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = false,
                            ReportedAt = new DateTime(2026, 9, 5, 19, 25, 0, 0, DateTimeKind.Utc),
                            Severity = "Major",
                            Status = "InProgress",
                            Title = "Hydrogen compressor seal-gas near miss",
                            Type = "NearMiss",
                            UpdatedAt = new DateTime(2026, 9, 8, 13, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CaseNumber = "SYN-2026-0020",
                            Description = "Two shell-course thickness readings in the inspection system do not match the signed field worksheet. Disposition is on hold pending instrument verification and source-record reconciliation.",
                            ProcessUnitName = "Tank Farm",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = false,
                            ReportedAt = new DateTime(2026, 9, 7, 9, 15, 0, 0, DateTimeKind.Utc),
                            Severity = "Moderate",
                            Status = "OnHold",
                            Title = "Tank inspection thickness records mismatch",
                            Type = "NonConformance",
                            UpdatedAt = new DateTime(2026, 9, 8, 14, 40, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CaseNumber = "SYN-2026-0021",
                            Description = "A temporary pedestrian diversion around hose testing was missing one directional sign. The route remained barricaded and the sign was installed during the inspection.",
                            ProcessUnitName = "Marine Terminal",
                            RefineryName = "Northstar Demonstration Refinery",
                            RegulatoryNotifiable = false,
                            ReportedAt = new DateTime(2026, 9, 8, 8, 30, 0, 0, DateTimeKind.Utc),
                            Severity = "Informational",
                            Status = "Open",
                            Title = "Temporary access route signage",
                            Type = "SafetyObservation",
                            UpdatedAt = new DateTime(2026, 9, 8, 11, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Oge.Refining.CaseApp.Infrastructure.Data.CaseTimelineRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("CaseTimelineEntries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AuthorName = "Control System Historian",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Cooling-water header pressure began falling from 5.1 bar; pump P-204B motor current fell from 42 A to 31 A while the standby pump remained in manual mode.",
                            EntryType = "ProcessData",
                            OccurredAt = new DateTime(2026, 9, 3, 13, 55, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AuthorName = "Control System Historian",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Overhead condenser outlet temperature rose from its 35 C baseline to 46 C. Pressure controller PC-101 output reached 92 percent.",
                            EntryType = "Alarm",
                            OccurredAt = new DateTime(2026, 9, 3, 14, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AuthorName = "Shift Supervisor",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Tower pressure reached the 2.4 bar high-high set point. The safeguard cut unit feed and routed vapour to flare; pressure returned below 1.9 bar at 14:38 UTC.",
                            EntryType = "Safeguard",
                            OccurredAt = new DateTime(2026, 9, 3, 14, 27, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            AuthorName = "Synthetic Reporter",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Incident opened after unit stabilization. No injury or exposure was reported; the eleven-minute flare event was referred for regulatory review.",
                            EntryType = "Reported",
                            OccurredAt = new DateTime(2026, 9, 3, 14, 35, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            AuthorName = "Rotating Equipment Engineer",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "P-204B was isolated. The outboard bearing had spalled rollers and heat discoloration; measured radial clearance was 0.31 mm against a 0.08-0.15 mm specification.",
                            EntryType = "Inspection",
                            OccurredAt = new DateTime(2026, 9, 3, 16, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            AuthorName = "Reliability Engineer",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Case SYN-2026-0009 recorded vibration rising from 4.1 to 8.7 mm/s. Inspection was deferred pending parts, and the operating log contained no compensating monitoring frequency or automatic standby-pump requirement.",
                            EntryType = "RecordsReview",
                            OccurredAt = new DateTime(2026, 9, 3, 17, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            AuthorName = "Investigation Lead",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "The board operator confirmed P-204A was available but its selector was left in manual after seal work. The low-header-pressure alarm required manual pump transfer and was acknowledged during simultaneous unit alarms.",
                            EntryType = "Interview",
                            OccurredAt = new DateTime(2026, 9, 4, 9, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            AuthorName = "Maintenance Planner",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Procedure MNT-14 requires a documented risk review, supervisor approval, expiry date, and compensating monitoring when equipment remains in service above the 7.1 mm/s vibration threshold. The SYN-2026-0009 attachment register contained no approval or monitoring plan, and the scheduled 2026-09-01 reading was blank.",
                            EntryType = "ProcedureReview",
                            OccurredAt = new DateTime(2026, 9, 4, 11, 40, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            AuthorName = "Control Systems Engineer",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Work order WO-4821 recorded P-204A seal testing on 2026-09-02. The DCS audit log shows its selector changed from Auto to Manual at 11:20 UTC; the work order closed at 12:05 UTC, with no later selector change before the incident.",
                            EntryType = "ConfigurationHistory",
                            OccurredAt = new DateTime(2026, 9, 4, 13, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            AuthorName = "Commissioning Engineer",
                            CaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "After P-204B bearing replacement, pump current stabilized at 43 A and cooling-water header pressure held at 5.2 bar. A simulated low-header condition started P-204A in 4 seconds with its selector in Auto; repeating the test in Manual produced no start command.",
                            EntryType = "FunctionalTest",
                            OccurredAt = new DateTime(2026, 9, 8, 9, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            AuthorName = "Process Engineer",
                            CaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "Shift reconciliation found no signed temperature-equilibration entry for catalyst lot CAT-26-0902.",
                            EntryType = "Reported",
                            OccurredAt = new DateTime(2026, 9, 2, 10, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            AuthorName = "Quality Specialist",
                            CaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "The loading checklist was complete except for the 180 C hold-point initials and duration.",
                            EntryType = "RecordsReview",
                            OccurredAt = new DateTime(2026, 9, 2, 13, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            AuthorName = "Unit Historian",
                            CaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "Historian data shows reactor temperature remained between 181 C and 184 C for 47 minutes before loading resumed.",
                            EntryType = "ProcessData",
                            OccurredAt = new DateTime(2026, 9, 3, 9, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            AuthorName = "Quality Specialist",
                            CaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "The console operator recalled announcing the hold-point completion but could not confirm who accepted it in the field.",
                            EntryType = "Interview",
                            OccurredAt = new DateTime(2026, 9, 4, 14, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            AuthorName = "Operations Superintendent",
                            CaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "Technical evidence supports equilibration; the record remains open for quality disposition and procedure-control review.",
                            EntryType = "DispositionReview",
                            OccurredAt = new DateTime(2026, 9, 7, 15, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AuthorName = "Area Operator",
                            CaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Content = "Work at the sample station paused when a contractor was observed wearing open safety glasses rather than sealed eyewear.",
                            EntryType = "Observation",
                            OccurredAt = new DateTime(2026, 8, 26, 11, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AuthorName = "Contractor Supervisor",
                            CaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Content = "The worker changed PPE before sampling resumed, and the crew reviewed the station-specific requirement.",
                            EntryType = "ImmediateAction",
                            OccurredAt = new DateTime(2026, 8, 26, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            AuthorName = "Safety Advisor",
                            CaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Content = "The permit referenced the general PPE matrix but omitted the sample-station eyewear note.",
                            EntryType = "ProcedureReview",
                            OccurredAt = new DateTime(2026, 8, 27, 9, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            AuthorName = "Area Supervisor",
                            CaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Content = "Field verification confirmed updated permit wording and sealed eyewear in use by the full crew.",
                            EntryType = "Verification",
                            OccurredAt = new DateTime(2026, 8, 27, 14, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            AuthorName = "Reliability Technician",
                            CaseId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Content = "Route reading measured 8.7 mm/s at the P-204B outboard bearing, up from 4.1 mm/s fourteen days earlier.",
                            EntryType = "ConditionMonitoring",
                            OccurredAt = new DateTime(2026, 8, 20, 8, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            AuthorName = "Maintenance Planner",
                            CaseId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Content = "Inspection was deferred pending delivery of the replacement bearing; no enhanced monitoring interval was entered.",
                            EntryType = "InspectionDeferral",
                            OccurredAt = new DateTime(2026, 8, 20, 13, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            AuthorName = "Rotating Equipment Engineer",
                            CaseId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Content = "P-204B was isolated under WO-4827 after the cooling-water event and bearing damage was confirmed.",
                            EntryType = "WorkOrder",
                            OccurredAt = new DateTime(2026, 9, 3, 18, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            AuthorName = "Maintenance Supervisor",
                            CaseId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Content = "The bearing assembly was replaced, alignment was corrected by 0.18 mm, and the pump returned to service.",
                            EntryType = "Repair",
                            OccurredAt = new DateTime(2026, 9, 5, 16, 25, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            AuthorName = "Reliability Engineer",
                            CaseId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Content = "Three post-repair readings remained between 3.2 and 3.5 mm/s with stable bearing temperature.",
                            EntryType = "Verification",
                            OccurredAt = new DateTime(2026, 9, 7, 10, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            AuthorName = "Environmental Console",
                            CaseId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Content = "Analyzer AIT-730 reported 18 ppm oil in water against the 15 ppm investigation threshold.",
                            EntryType = "Alarm",
                            OccurredAt = new DateTime(2026, 9, 4, 7, 40, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            AuthorName = "Wastewater Operator",
                            CaseId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Content = "Final effluent was routed through the containment basin while grab samples were collected.",
                            EntryType = "Containment",
                            OccurredAt = new DateTime(2026, 9, 4, 7, 48, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            AuthorName = "Instrument Technician",
                            CaseId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Content = "The analyzer zero check showed a positive drift of 6 ppm; cleaning restored the expected response.",
                            EntryType = "CalibrationCheck",
                            OccurredAt = new DateTime(2026, 9, 4, 10, 35, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            AuthorName = "Environmental Laboratory",
                            CaseId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Content = "The first two retained samples measured 9 ppm and 10 ppm. One confirmatory split sample remains pending.",
                            EntryType = "LaboratoryResult",
                            OccurredAt = new DateTime(2026, 9, 6, 12, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            AuthorName = "Environmental Lead",
                            CaseId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Content = "The event remains open and notifiable pending the confirmatory result and completion of the discharge-duration calculation.",
                            EntryType = "RegulatoryReview",
                            OccurredAt = new DateTime(2026, 9, 8, 16, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            AuthorName = "Control System Historian",
                            CaseId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Content = "Seal-gas differential pressure fell to 0.7 bar and the compressor unloaded automatically in 1.8 seconds.",
                            EntryType = "Alarm",
                            OccurredAt = new DateTime(2026, 9, 5, 19, 25, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            AuthorName = "Shift Supervisor",
                            CaseId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Content = "The standby seal-gas source established pressure before the trip threshold; fixed gas detectors remained at zero.",
                            EntryType = "Safeguard",
                            OccurredAt = new DateTime(2026, 9, 5, 19, 27, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            AuthorName = "Machinery Engineer",
                            CaseId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Content = "No seal damage was found. Regulator PCV-612 exhibited delayed stem travel during bench testing.",
                            EntryType = "Inspection",
                            OccurredAt = new DateTime(2026, 9, 6, 8, 40, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            AuthorName = "Control Systems Engineer",
                            CaseId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Content = "Trip and unload set points matched the approved cause-and-effect chart; no recent logic changes were present.",
                            EntryType = "ConfigurationHistory",
                            OccurredAt = new DateTime(2026, 9, 7, 11, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000005"),
                            AuthorName = "Investigation Lead",
                            CaseId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Content = "Metallurgy and maintenance-history reviews are in progress before the regulator failure mechanism is determined.",
                            EntryType = "InvestigationUpdate",
                            OccurredAt = new DateTime(2026, 9, 8, 13, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            AuthorName = "Integrity Engineer",
                            CaseId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Content = "Inspection-system values for locations C2-14 and C2-15 differed from the signed worksheet by 0.8 mm and 0.9 mm.",
                            EntryType = "RecordsReview",
                            OccurredAt = new DateTime(2026, 9, 7, 9, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            AuthorName = "Inspection Manager",
                            CaseId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Content = "The remaining-life calculation and inspection closeout were placed on hold.",
                            EntryType = "DataHold",
                            OccurredAt = new DateTime(2026, 9, 7, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000003"),
                            AuthorName = "NDE Coordinator",
                            CaseId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Content = "Calibration blocks and the ultrasonic instrument passed verification with no reportable variance.",
                            EntryType = "InstrumentCheck",
                            OccurredAt = new DateTime(2026, 9, 8, 9, 25, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000004"),
                            AuthorName = "Integrity Engineer",
                            CaseId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Content = "Original acquisition files were requested from the inspection vendor to determine which values were transcribed incorrectly.",
                            EntryType = "Reconciliation",
                            OccurredAt = new DateTime(2026, 9, 8, 14, 40, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            AuthorName = "Marine Safety Representative",
                            CaseId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Content = "One directional sign was missing from the barricaded pedestrian diversion around hose pressure testing.",
                            EntryType = "Observation",
                            OccurredAt = new DateTime(2026, 9, 8, 8, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000002"),
                            AuthorName = "Terminal Operator",
                            CaseId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Content = "A replacement sign was installed and the route was walked from both approaches.",
                            EntryType = "ImmediateAction",
                            OccurredAt = new DateTime(2026, 9, 8, 8, 42, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000003"),
                            AuthorName = "Marine Supervisor",
                            CaseId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Content = "The observation remains open until the next-shift pre-job briefing verifies the temporary traffic plan.",
                            EntryType = "FollowUp",
                            OccurredAt = new DateTime(2026, 9, 8, 11, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Oge.Refining.CaseApp.Infrastructure.Data.CaseTimelineRecord", b =>
                {
                    b.HasOne("Oge.Refining.CaseApp.Infrastructure.Data.CaseRecord", "Case")
                        .WithMany("Timeline")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Oge.Refining.CaseApp.Infrastructure.Data.CaseRecord", b =>
                {
                    b.Navigation("Timeline");
                });
#pragma warning restore 612, 618
        }
    }
}
